# Generated by Django 4.0.3 on 2022-05-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='news/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('post_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'list of news',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tgas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250)),
                ('post_time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.news')),
            ],
            options={
                'verbose_name': 'Reviews',
                'ordering': ['post_time_created'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.tag'),
        ),
    ]
