# Generated by Django 4.0.3 on 2022-05-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-post_time_created'], 'verbose_name': 'list of news'},
        ),
    ]
