# Generated by Django 4.0.3 on 2022-05-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-post_time_created'], 'verbose_name': 'list of new'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['post_time_created'], 'verbose_name': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag'},
        ),
    ]
