# Generated by Django 4.0.3 on 2022-05-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_alter_news_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Tag'},
        ),
    ]
