# Generated by Django 4.0.3 on 2022-05-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_ip_news_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='ip',
        ),
    ]
