# Generated by Django 4.0.3 on 2022-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_rename_views_news_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
