# Generated by Django 4.0.3 on 2022-05-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_news_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='session',
        ),
    ]
